### ISSUE TITLE
Cost/Rarity not showing up for ships at the detail level, only at the table summary level

### ISSUE THREAD

**Issue by bknowles** [karrde/ffg_swrpg#43]
So, I know I've reported this one before, and I've been told that it's fixed.

But now we have another person who has reported the same problem -- see [https://community.fantasyflightgames.com/topic/215915-coming-soon-to-an-index-near-you/#entry2146314](https://community.fantasyflightgames.com/topic/215915-coming-soon-to-an-index-near-you/#entry2146314).

Here's a screenshot of the detail page for a starfighter showing the problem:

[https://www.dropbox.com/s/e5u45g438v6g8df/Screen%20Shot%202016-04-03%20at%202.11.00%20PM.png?dl=0](https://www.dropbox.com/s/e5u45g438v6g8df/Screen%20Shot%202016-04-03%20at%202.11.00%20PM.png?dl=0)

Here's a screenshot of the table summary index for the same starfighter:

[https://www.dropbox.com/s/zin964m4m0syu4g/Screen%20Shot%202016-04-03%20at%202.12.35%20PM.png?dl=0](https://www.dropbox.com/s/zin964m4m0syu4g/Screen%20Shot%202016-04-03%20at%202.12.35%20PM.png?dl=0)

These examples are from the same one reported by Braendig at [http://swrpg.viluppo.net/transportation/starships/2828/](http://swrpg.viluppo.net/transportation/starships/2828/)

**Comment by karrde** [comment]
Fixed with graphics update
